#####Purpose of the code: convert pdf files to .txt files
#####with xpdf and check if all have been converted
#####after the conversion suitably formatted txt files have to be selected manually for further processing (e.g. by deleting the rest)

#####START - Settings and explanations-----------------------
setwd("C:\\Users\\Male\\Documents\\test")
#assumption: this folder contains ONLY the pdf documents to be converted

#xpdf has to be installed in the respective folder, here
# "C:/Program Files/xpdfbin-win-3.04/bin32/pdftotext.exe"
pdftotextdir <- "C:/Program Files/xpdfbin-win-3.04/bin32/pdftotext.exe"


#for definitions of output formats of txt files see xpdf documentation: "", "-table", "-layout", "-raw"  (the "" format will be named as noformat)
#in most cases layout is suitable which keeps the original layout as good as possible (does not include character formatting such as bold)
#depending on the structure of the pdf file, different xpdf output formats might apply for further analysis

#in case the text is written in  "two-columns-style" 
#a plain text flow in "single column style" is generated by: 
#outputformats <- c("") 
#other output formats keep the two columns
outputformats <- c("", "-table", "-layout", "-raw")

#####END - Settings and explanations-----------------------


#START convert files to text--------------------------------
#read all files in folder - assumed there are only pdf files (there was a problem with pdf files ending on .PDF - upper case - therefore all files are read in to be on the safe side - Rfiles and history do not show up by this request)
files <- list.files(pattern="")

#apply xpdf conversion on all files using the pre defined output formats
invisible(lapply(files, function(i) {

  sapply(outputformats, function(f) {

    filename <- paste(substr(f, 2, nchar(f)), "_", substr(i, 1, nchar(i)-4), "_UTF8", ".txt", sep = "") #extension of the filename by the output format
    
    #in case the noformat is used filename has to be corrected
    if (substr(filename, 1,1) == "_") {
      filename <- paste("noformat", filename, sep="")
    }
  
    #as fas as possible passwords are ignored and output encoding is set to UTF8
    system(paste(paste("\"", pdftotextdir, "\"", sep=""), "-enc UTF-8",  f, "-opw password", "-upw password",  i, filename), wait=FALSE)

})
}))

#END convert files to text--------------------------------


#START - check if any files have not been converted (e.g. due to document security issues)------------------
files <- list.files(pattern=".txt")
txtfiles <- paste(files, collapse = " ")

invisible(sapply(files, function(i) {
    
 if (grepl(substr(i, 1 , nchar(i)-5), txtfiles, fixed = TRUE)==FALSE) {
    print(paste("WARNING <<<<<< Document not converted:", i ,sep = " "))
  }
 
}))
#END - check if any files have not been converted (e.g. due to document security issues)-----------------


rm(list = ls()) #clear workspace
